#!/bin/bash

RM_1ST=0
[[ "$1" == "--rm" ]] && shift && RM_1ST=1


SRC=./meijue-ui/build/outputs/aar/
# DST=../../DemoApp32/foliage/libs
DST=../../Foliage/demo-app-as32.foliage/foliage/libs


case $1 in
    local|lo|copy|aar)
        shift
        [[ $RM_1ST -eq 1 ]] && rm -rf meijue-ui/build
        ./gradlew :meijue-ui:build $* && {
          if [[ -f "$SRC/meijue-ui-debug.aar" ]]; then
            cp -v "$SRC/meijue-ui-debug.aar" $DST/
          fi
        }
        ;;
    copy|cp)
        # ls -la "$SRC/meijue-ui-debug.aar"
        if [[ -f "$SRC/meijue-ui-debug.aar" ]]; then
          cp -v "$SRC/meijue-ui-debug.aar" $DST/
        fi
        ;;
    *)
        ./gradlew bintrayUpload $*
        ;;
esac

